### PR TITLE
Adds elasticsearch logger

### PR DESCRIPTION
**Pull request by techjacker**

### CODE REVIEW

**Comment by techjacker** [comment]
Added healthcheck command to Dockerfile

**Review by danielepolencic — APPROVED** [review]
I'd rather NOT use docker-wait. If you can, use the [HEALTHCHECK](https://docs.docker.com/engine/reference/builder/#healthcheck)

**Comment by techjacker** [comment]
I've added `HEALTHCHECK` to the Dockerfile.

As far as I can tell doing this merely adds a property to the container metadata (health status), it doesn't delay execution of the container `CMD`.

So we still need the polling script triggered by docker-compose to get a local development environment set up with `docker compose up`.

**Comment by danielepolencic** [comment]
According to this, it should: https://github.com/docker/compose/pull/4163#issuecomment-279802141

**Comment by techjacker** [comment]
Ok I'll try to get that method working

**Comment by danielepolencic** [comment]
Since you have it working, I don't want to stop you merging this PR in.

If you envision this being a sizeable chunk of work, it's better to factor that in a different PR.

**Comment by techjacker** [comment]
reverted docker compose to v2.1 so could remove `HEALTHCHECK` from the dockerfile (which was failing the CI build as drone is running < docker 1.2)

**Pull request merged**
